### ISSUE TITLE
1.5.0-9 & 1.5.0-11 Flight Spell Effect doesn't work correctly [bug]

### ISSUE THREAD

**Issue by garnichtpascal** [Growlith1223/ArsMagica2#100]
When you have the Flight effect from the flight spell it doesn't work. You can't fly, but you get no falldamage.

**Comment by Zieg777** [comment]
Perhaps similar to Levitate? I never really used levitate in the past because I never knew what it did. Right now though in 1.5.0-11, it's basically a flight spell. Only problem is if I log off while it is active, I still have the effect on log-in, but I can't fly anymore. Casting again doesn't work, but I have to wait for the effect to end before casting it again.

**Comment by garnichtpascal** [comment]
Levitation is the flight spell, but with slower flight speed.

**Comment by Growlith1223** [comment]
fixed
