### ISSUE TITLE
AM2 1.5.0-15 Prosperity does not seem to function.

### ISSUE THREAD

**Issue by Lonemind** [Growlith1223/ArsMagica2#158]
I created a dig spell with prosperity x3 on it but it doesn't seem to multiply drops.
I've tried it on ores and more specifically on gravel. In 1.7.10 gravel would always turn to flint. In this version gravel is unaffected.
Also, to note, when I look at the spells tooltip it says it has Fortune IX and Looting IX. My heart skipped a beat when I saw that then was disappointed when I found it did nothing. Haha.

**Comment by Growlith1223** [comment]
from what i remember looking at the code, it doesn't even use prosperity at all but regardless, i'll look into it and fix it, im a bit busy with other things(family related, and whatnot) but once i am done with that, i'll get working on ars magica again.

To anyone that is worried that i'll drop this, i won't, i can trust you that(not for a very long time at least), i plan to keep this going for as long as i can, i may take a few breaks here and there due to lack of motivation but i can promise you, i didn't quit.

**Comment by Lonemind** [comment]
If I understand correctly, Prosperity uses the enchantment mechanic. Essentially, when you hold it or select it in the spell book it enchants the book with Looting/Fortune and when the spell triggers takes that into account. For instance, you can cast a zone damage spell without prosperity, switch to a sword that has looting 3 on it and that looting will apply to the zone damage. Same for Dig. You can make a zone quarry spell without prosperity or feather touch, cast it and then switch to a Silk Touch pickaxe/tool and have that enchantment apply to the zone.
Knowing nothing of coding myself I mention this only to point you in the right direction of why Prosperity doesn't seem to be used anywhere by spells.
Thanks for all your hard work Growlith. AM2 is my favorite mod and it'd be a shame to see it die out. XD

**Comment by Growlith1223** [comment]
This is half fixed, it should be fixed for fortune-based spells(mining), combat is not fixed yet however
