### ISSUE TITLE
Flight not working on server

### ISSUE THREAD

**Issue by Mowmaster** [Growlith1223/ArsMagica2#252]
Playing on Tlovetechs modpack for 1.10.2 flight seems to work fine in single player but doesnt in multiplayer. 
I am currently using a Self & Projectile spell of Flight+Buff Power x3+ Duration x3
It gives the effect but when you double tap it doesnt let you fly, using projectile on other players doesnt allow them to fly either along with just giving it to other player to use themselves also doesnt work (incase it was only effecting me)
As its pricey i havent tested lower potencies of this yet.

**Comment by TheIcyOne** [comment]
Confirmed that this occurs in latest build as of cbac4b0, looking into a fix now.

**Comment by Sedastian** [comment]
Be sure that the server allows flight?

**Comment by Mowmaster** [comment]
Server allows all other kinds of flight but I haven't asked about that specifically  yet

**Comment by xenxero1** [comment]
A good portion of flight mechanics bypass server flight restrictions. Oddly though, in my experience it just kicks you rather than preventing the method all together. If the server were to disallow flight that is. It seems that in any case, you should be able to take off -- or be kicked with the corresponding flight message.

**Comment by Mowmaster** [comment]
That is correct, I have never been on a server where it completely disallows the player to fly, as it kicks them a short time later until the configuration is fixed.

**Comment by TheIcyOne** [comment]
Yeah, it's an issue with AM2 itself, irrespective of the server software.
