### ISSUE TITLE
Slipstream Generator does not do anything

### ISSUE THREAD

**Issue by Zieg777** [Growlith1223/ArsMagica2#38]
The slipstream generator/elevator thingy doesn't do anything. At least not when powered with neutral etherium.

It also breaks instantly with a hand.

**Comment by jsuereth** [comment]
This is a recent break, caused by: 

https://github.com/Growlith1223/ArsMagica2/compare/v1.5.0-6...v1.5.0-9#diff-8e4a757167d4981f0329ac2e30be92ecR36


I think you're actually moving, it's just the client doesn't see it as the slipstream generating isn't forcing a sync packet.   I'm not sure why that line was removed.

**Comment by jsuereth** [comment]
made a bootleg release of my own local copy and confirmed.  Removing the world.isRemote check fixes this.  My kids will be elated AND elevated once more.

**Comment by Growlith1223** [comment]
consequences of working on performance lol, im aware of it, just haven't gotten around to fixing it.

**Comment by jsuereth** [comment]
If you want I can submit the fix.  Might as well contribute back if I can.  I'm already running it on the home server.
